export const PARTNERS = [
  { name: 'Apple', slug: 'apple' },
  { name: 'Google', slug: 'google' },
  { name: 'Meta', slug: 'meta' },
  { name: 'Netflix', slug: 'netflix' },
  { name: 'Tesla', slug: 'tesla' },
  { name: 'Samsung', slug: 'samsung' },
  { name: 'Intel', slug: 'intel' },
  { name: 'NVIDIA', slug: 'nvidia' },
  { name: 'Cisco', slug: 'cisco' },
  { name: 'Dell', slug: 'dell' },
  { name: 'HP', slug: 'hp' },
  { name: 'Sony', slug: 'sony' },
  { name: 'Spotify', slug: 'spotify' },
  { name: 'Uber', slug: 'uber' },
  { name: 'Airbnb', slug: 'airbnb' },
  { name: 'PayPal', slug: 'paypal' },
  { name: 'Visa', slug: 'visa' },
  { name: 'MasterCard', slug: 'mastercard' },
  { name: 'Nike', slug: 'nike' },
  { name: 'Coca-Cola', slug: 'cocacola' },
  { name: "McDonald's", slug: 'mcdonalds' },
  { name: 'Toyota', slug: 'toyota' },
  { name: 'BMW', slug: 'bmw' },
  { name: 'Starbucks', slug: 'starbucks' },
  { name: 'X', slug: 'x' },
  { name: 'TikTok', slug: 'tiktok' },
  { name: 'Shopify', slug: 'shopify' },
  { name: 'Stripe', slug: 'stripe' },
  { name: 'Google Cloud', slug: 'googlecloud' },
  { name: 'FedEx', slug: 'fedex' },
  { name: 'Boeing', slug: 'boeing' },
  { name: 'Volkswagen', slug: 'volkswagen' },
  { name: 'Honda', slug: 'honda' },
  { name: 'Ford', slug: 'ford' },
  { name: 'Siemens', slug: 'siemens' },
  { name: 'Accenture', slug: 'accenture' },
] as const
